export type IconType =
  | 'xmark-solid'
  | 'wrench-solid'
  | 'tags-solid'
  | 'tag-solid'
  | 'square-check-solid'
  | 'spinner-solid'
  | 'sort-up-solid'
  | 'sort-solid'
  | 'sort-down-solid'
  | 'rectangle-xmark-solid'
  | 'question-circle'
  | 'plus-square'
  | 'person'
  | 'person-o'
  | 'person-circle'
  | 'pen-to-square-solid'
  | 'more'
  | 'magnifying-glass-solid'
  | 'location-dot-solid'
  | 'list'
  | 'link-45deg'
  | 'layer-group-solid'
  | 'house-solid'
  | 'hashtag-solid'
  | 'handshake-regular'
  | 'hand-thumbs-up'
  | 'hand-thumbs-up-fill'
  | 'hammer-solid'
  | 'gift-fill'
  | 'gear-solid'
  | 'filter-solid'
  | 'filter-circle-xmark-solid'
  | 'file-import-solid'
  | 'eye'
  | 'eye-slash'
  | 'eye-fill'
  | 'exclamation-triangle'
  | 'exclamation-circle'
  | 'envelope'
  | 'envelope-fill'
  | 'dollar-sign-solid'
  | 'desktop-solid'
  | 'cubes-solid'
  | 'cube-solid'
  | 'cross'
  | 'content-copy'
  | 'coin'
  | 'clock'
  | 'circle-xmark-solid'
  | 'circle-xmark-regular'
  | 'circle-pause-solid'
  | 'circle-check-solid'
  | 'check-lg'
  | 'check-circle'
  | 'chat-text'
  | 'chart-pie-solid'
  | 'chart-line-solid'
  | 'cart-shopping-solid'
  | 'caret-up-solid'
  | 'caret-right-solid'
  | 'caret-left-solid'
  | 'caret-down-solid'
  | 'calendar-days-solid'
  | 'building-shield-solid'
  | 'boxes-packing-solid'
  | 'box-solid'
  | 'box-arrow-in-right'
  | 'box-archive-solid'
  | 'bookmark'
  | 'bookmark-fill'
  | 'arrows-rotate-solid'
  | 'arrow-up-wide-short-solid'
  | 'arrow-up-solid'
  | 'arrow-right-solid'
  | 'arrow-left-solid'
  | 'arrow-left-right'
  | 'arrow-down-solid'
  | 'arrow-down-short-wide-solid'
  | 'angles-up-solid'
  | 'angles-right-solid'
  | 'angles-left-solid'
  | 'angles-down-solid'
  | 'angle-up-solid'
  | 'angle-right-solid'
  | 'angle-left-solid'
  | 'angle-down-solid';

export const ICONS_CODEPOINTS: { [key in IconType]: string } = {
  'xmark-solid': '61697',
  'wrench-solid': '61698',
  'tags-solid': '61699',
  'tag-solid': '61700',
  'square-check-solid': '61701',
  'spinner-solid': '61702',
  'sort-up-solid': '61703',
  'sort-solid': '61704',
  'sort-down-solid': '61705',
  'rectangle-xmark-solid': '61706',
  'question-circle': '61707',
  'plus-square': '61708',
  'person': '61709',
  'person-o': '61710',
  'person-circle': '61711',
  'pen-to-square-solid': '61712',
  'more': '61713',
  'magnifying-glass-solid': '61714',
  'location-dot-solid': '61715',
  'list': '61716',
  'link-45deg': '61717',
  'layer-group-solid': '61718',
  'house-solid': '61719',
  'hashtag-solid': '61720',
  'handshake-regular': '61721',
  'hand-thumbs-up': '61722',
  'hand-thumbs-up-fill': '61723',
  'hammer-solid': '61724',
  'gift-fill': '61725',
  'gear-solid': '61726',
  'filter-solid': '61727',
  'filter-circle-xmark-solid': '61728',
  'file-import-solid': '61729',
  'eye': '61730',
  'eye-slash': '61731',
  'eye-fill': '61732',
  'exclamation-triangle': '61733',
  'exclamation-circle': '61734',
  'envelope': '61735',
  'envelope-fill': '61736',
  'dollar-sign-solid': '61737',
  'desktop-solid': '61738',
  'cubes-solid': '61739',
  'cube-solid': '61740',
  'cross': '61741',
  'content-copy': '61742',
  'coin': '61743',
  'clock': '61744',
  'circle-xmark-solid': '61745',
  'circle-xmark-regular': '61746',
  'circle-pause-solid': '61747',
  'circle-check-solid': '61748',
  'check-lg': '61749',
  'check-circle': '61750',
  'chat-text': '61751',
  'chart-pie-solid': '61752',
  'chart-line-solid': '61753',
  'cart-shopping-solid': '61754',
  'caret-up-solid': '61755',
  'caret-right-solid': '61756',
  'caret-left-solid': '61757',
  'caret-down-solid': '61758',
  'calendar-days-solid': '61759',
  'building-shield-solid': '61760',
  'boxes-packing-solid': '61761',
  'box-solid': '61762',
  'box-arrow-in-right': '61763',
  'box-archive-solid': '61764',
  'bookmark': '61765',
  'bookmark-fill': '61766',
  'arrows-rotate-solid': '61767',
  'arrow-up-wide-short-solid': '61768',
  'arrow-up-solid': '61769',
  'arrow-right-solid': '61770',
  'arrow-left-solid': '61771',
  'arrow-left-right': '61772',
  'arrow-down-solid': '61773',
  'arrow-down-short-wide-solid': '61774',
  'angles-up-solid': '61775',
  'angles-right-solid': '61776',
  'angles-left-solid': '61777',
  'angles-down-solid': '61778',
  'angle-up-solid': '61779',
  'angle-right-solid': '61780',
  'angle-left-solid': '61781',
  'angle-down-solid': '61782',
};
