import './globals.css';
import '../fonts/icons.css';

import type { Metadata } from 'next';
import { ReactNode } from 'react';

import Navbar from '@/components/Navbar';
import SideMenu from '@/components/SideMenu';
import { CommonConstant } from '@/constant';

import Providers from './providers';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

// ref: https://www.creative-tim.com/twcomponents/component/layout-with-header-sidebar-and-rightbar
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-900">
        <Providers>
          <div className="w-screen h-screen relative">
            <Navbar className="absolute top-0 left-0" />
            <div className="flex h-full pt-14">
              <SideMenu list={CommonConstant.SIDE_MENU_LIST} />
              <main className="flex flex-col w-full h-full  overflow-x-hidden overflow-y-auto">{children}</main>
              {/* <Rightbar /> */}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
